# Generated by Django 5.1.4 on 2025-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='paciente_pa_nombre_596ee7_idx')],
            },
        ),
    ]
