# Generated by Django 5.1.4 on 2025-04-22 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('curp', models.CharField(help_text='18 caracteres según el formato oficial de la CURP.', max_length=18, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='CURP inválida.', regex='^[A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d]\\d$')], verbose_name='CURP')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Introduzca 10 dígitos.')], verbose_name='teléfono')),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(120, 'La edad máxima permitida es 120 años.')])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / No binario'), ('N', 'No declarado')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='paciente_pa_apellid_9aeea8_idx')],
            },
        ),
    ]
