# Generated by Django 5.1.4 on 2025-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctores',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='doctor_doct_apellid_2f9e64_idx')],
            },
        ),
    ]
