# Generated by Django 5.1.4 on 2025-04-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
