# Generated by Django 5.1.4 on 2025-04-22 10:53

import django.db.models.deletion
import django.utils.timezone
import estudio.models
import estudio.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('dicom_file', models.FileField(storage=estudio.storage_backends.DicomAzureStorage(), upload_to=estudio.models.dicom_upload_path)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='doctor.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='paciente.paciente')),
            ],
            options={
                'ordering': ('-fecha',),
                'indexes': [models.Index(fields=['paciente', 'fecha'], name='estudio_est_pacient_f2c031_idx')],
            },
        ),
    ]
