# Generated by Django 5.1.4 on 2025-04-24 00:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('study_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='paciente.paciente')),
            ],
            options={
                'ordering': ('-fecha',),
                'indexes': [models.Index(fields=['paciente', 'fecha'], name='estudio_est_pacient_f2c031_idx')],
            },
        ),
    ]
