# Generated by Django 5.1.4 on 2025-04-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='doctor',
        ),
    ]
