# Generated by Django 5.1.4 on 2025-04-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.BooleanField(default=False)),
                ('vigencia', models.DateTimeField()),
                ('link', models.URLField(unique=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='estudio.estudio')),
            ],
        ),
    ]
